### ISSUE TITLE
Html presentations don't work as stand-alone files (images break)

### ISSUE THREAD

**Issue by jessepharrison** [csc-training/slide-template#7]
- Html presentations created using `slidefactory.simg` only work when the html file is located in the `slide-template` folder, or if the `img` folder is copied to the new location alongside the html file. Otherwise image embedding breaks. 
- Tested with `example.html` and a separate presentation using a custom theme, either by moving the html somewhere else on a laptop or publishing the file on Allas.
- The issue seems specific to this version of the Pandoc slide template, it works OK using the older `pandoc.sif`.

**Comment by jessepharrison** [comment]
Managed to find a workaround for custom themes using `pandoc.sif` / `pandoc-eurocc.sif`.
It's not perfect (and required some manual tweaking), but does the job :-)

https://github.com/BioDT/biodt-pandoc

**Comment by mlouhivu** [comment]
Yes, it is expected as the html file includes references to local files. Embedding images is one solution, the other would be to use only references to online assets.
Pandoc had a bug in embedding remote css files (fixed in recent versions) that still affects us, but a work-around is to only use local files when doing the conversion with `--self-contained`. Current version includes this work-around, so it should work also for you.
Btw. the other containers you mentioned are later derivative works that borrowed many of the files from this repo, but are otherwise separate efforts.
